const List<Map<String, dynamic>> crossFitEvent = [
  {
    "Name": "Cross Fit 4",
    "Seat": "10/10",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event4.png",
  },
  {
    "Name": "Cross Fit 5",
    "Seat": "15/15",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event5.png",
  },
  {
    "Name": "Cross Fit 6",
    "Seat": "20/20",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event6.png",
  },
  {
    "Name": "Cross Fit 7",
    "Seat": "10/10",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event7.png",
  },
  {
    "Name": "Cross Fit 1",
    "Seat": "15/13",
    "Seats Left": "(2 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event1.png",
  },
  {
    "Name": "Cross Fit 2",
    "Seat": "17/12",
    "Seats Left": "(5 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event2.png",
  },
  {
    "Name": "Cross Fit 3",
    "Seat": "20/10",
    "Seats Left": "(10 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event3.png",
  },
  {
    "Name": "Cross Fit 8",
    "Seat": "15/15",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event8.png",
  },
  {
    "Name": "Cross Fit 9",
    "Seat": "20/20",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event9.png",
  },
  {
    "Name": "Cross Fit 10",
    "Seat": "10/10",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event10.png",
  },
  {
    "Name": "Cross Fit 11",
    "Seat": "15/15",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event11.png",
  },
  {
    "Name": "Cross Fit 12",
    "Seat": "20/20",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event12.png",
  },
];
