const List<Map<String, dynamic>> heavyLiftingEvent = [
  {
    "Name": "Heavy Lifting 1",
    "Seat": "15/13",
    "Seats Left": "(2 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event1.png",
  },
  {
    "Name": "Heavy Lifting 2",
    "Seat": "17/12",
    "Seats Left": "5 seats left",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event2.png",
  },
  {
    "Name": "Heavy Lifting 3",
    "Seat": "20/10",
    "Seats Left": "(10 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event3.png",
  },
  {
    "Name": "Heavy Lifting 4",
    "Seat": "10/10",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event4.png",
  },
  {
    "Name": "Heavy Lifting 5",
    "Seat": "15/15",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event5.png",
  },
  {
    "Name": "Heavy Lifting 6",
    "Seat": "20/20",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event6.png",
  },
  {
    "Name": "Heavy Lifting 7",
    "Seat": "10/10",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event7.png",
  },
  {
    "Name": "Heavy Lifting 8",
    "Seat": "15/15",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event8.png",
  },
  {
    "Name": "Heavy Lifting 9",
    "Seat": "20/20",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event9.png",
  },
  {
    "Name": "Heavy Lifting 10",
    "Seat": "10/10",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event10.png",
  },
  {
    "Name": "Heavy Lifting 11",
    "Seat": "15/15",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event11.png",
  },
  {
    "Name": "Heavy Lifting 12",
    "Seat": "20/20",
    "Seats Left": "(0 seats left)",
    "Time": "8:00 PM - 10: 00 AM",
    "assets": "assets/events/event12.png",
  },
];
